FROM mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2019

RUN mkdir Setup \
&& powershell -Command (Invoke-WebRequest -Uri "https://download.microsoft.com/download/B/D/E/BDE8FAD6-33E5-44F6-B714-348F73E602B6/SQLEXPR_x64_ENU.exe" -OutFile C:/Setup/setup.exe) \
&& C:/Setup/setup.exe /q /ACTION=Install /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD=qGH6RFvq /SQLSVCACCOUNT="NT AUTHORITY\System" /SQLSYSADMINACCOUNTS="BUILTIN\Administrators" /TCPENABLED=1 /IACCEPTSQLSERVERLICENSETERMS /SQLCOLLATION=Polish_CI_AS \
&& powershell -Command (Invoke-WebRequest -Uri "https://download.microsoft.com/download/4/5/8/458f51ca-246e-400a-a047-38f5cccf1d49/SQLServer2012-KB4583465-x64.exe" -OutFile C:/Setup/patch.exe) \
&& C:/Setup/patch.exe /quiet /ACTION=Patch /INSTANCENAME=MSSQLSERVER /IACCEPTSQLSERVERLICENSETERMS \
&& rmdir /S /Q Setup

COPY start.ps1 /

ENV SA_PASSWORD=_ ACCEPT_EULA=_

CMD powershell -Command (C:/start.ps1 -SA_PASSWORD $env:SA_PASSWORD -ACCEPT_EULA $env:ACCEPT_EULA -Verbose)