FROM mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2016

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

RUN mkdir C:/Setup

COPY en_sql_server_2019_developer_x64_dvd_baea4195 C:/Setup
COPY SQLServer2019-KB5008996-x64.exe C:/Setup/patch.exe

ARG SQLCOLLATION
RUN Write-Host $env:SQLCOLLATION ; \
C:/Setup/setup.exe /q /ACTION=Install /FEATURES=SQLENGINE /INSTANCENAME=MSSQLSERVER /SECURITYMODE=SQL /SAPWD=qGH6RFvq /SQLSVCACCOUNT='NT AUTHORITY\System' /SQLSYSADMINACCOUNTS='BUILTIN\Administrators' /TCPENABLED=1 /IACCEPTSQLSERVERLICENSETERMS /SQLCOLLATION=$env:SQLCOLLATION ; \
C:/Setup/patch.exe /quiet /ACTION=Patch /INSTANCENAME=MSSQLSERVER /IACCEPTSQLSERVERLICENSETERMS

RUN rm C:/Setup -recurse

COPY start.ps1 /
ENV SA_PASSWORD=_ ACCEPT_EULA=_
CMD C:/start.ps1 -SA_PASSWORD $env:SA_PASSWORD -ACCEPT_EULA $env:ACCEPT_EULA -Verbose