docker push cagrin/mssql-server-oldies:2012-latest
docker push cagrin/mssql-server-oldies:2012-latest-pl
docker push cagrin/mssql-server-oldies:2014-latest
docker push cagrin/mssql-server-oldies:2014-latest-pl
docker push cagrin/mssql-server-oldies:2016-latest
docker push cagrin/mssql-server-oldies:2016-latest-pl
docker push cagrin/mssql-server-oldies:2017-latest
docker push cagrin/mssql-server-oldies:2017-latest-pl
docker push cagrin/mssql-server-oldies:2019-latest
docker push cagrin/mssql-server-oldies:2019-latest-pl