name: Build and test Express
on:
  workflow_dispatch:

jobs:
  build-2012-express-pl:
    name: Build and test 2012-express-pl
    runs-on: windows-2019
    env:
      IMAGE_NAME: cagrin/mssql-server-oldies
      TAG_NAME: 2012-express-pl
      PRODUCT_VERSION: 11.0.7507.2
      MSSQL_COLLATION: Polish_CI_AS
    steps:
    - uses: actions/checkout@master
    - name: Build image
      shell: pwsh
      run: |
        cd express/2012-latest
        docker build -m 4g -t ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} .
    - name: Test image
      shell: pwsh
      run: |
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Password." -p 51433:1433 -d ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
        Start-Sleep -Second 10
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "Password." -Query "IF SERVERPROPERTY('ProductVersion') <> '${{ env.PRODUCT_VERSION }}' RAISERROR ('ProductVersion is invalid', 16, 1)"
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "Password." -Query "IF SERVERPROPERTY('Collation') <> '${{ env.MSSQL_COLLATION }}' RAISERROR ('Collation is invalid', 16, 1)"
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "Password." -Query "IF SERVERPROPERTY('Edition') <> 'Express Edition (64-bit)' RAISERROR ('Edition is invalid', 16, 1)"
  build-2014-express-pl:
    name: Build and test 2014-express-pl
    runs-on: windows-2019
    env:
      IMAGE_NAME: cagrin/mssql-server-oldies
      TAG_NAME: 2014-express-pl
      PRODUCT_VERSION: 12.0.6433.1
      MSSQL_COLLATION: Polish_CI_AS
    steps:
    - uses: actions/checkout@master
    - name: Build image
      shell: pwsh
      run: |
        cd express/2014-latest
        docker build -m 4g -t ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }} .
    - name: Test image
      shell: pwsh
      run: |
        docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=Password." -p 51433:1433 -d ${{ env.IMAGE_NAME }}:${{ env.TAG_NAME }}
        Start-Sleep -Second 10
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "Password." -Query "IF SERVERPROPERTY('ProductVersion') <> '${{ env.PRODUCT_VERSION }}' RAISERROR ('ProductVersion is invalid', 16, 1)"
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "Password." -Query "IF SERVERPROPERTY('Collation') <> '${{ env.MSSQL_COLLATION }}' RAISERROR ('Collation is invalid', 16, 1)"
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "Password." -Query "IF SERVERPROPERTY('Edition') <> 'Express Edition (64-bit)' RAISERROR ('Edition is invalid', 16, 1)"