name: Build and test 2014-express-pl
on:
  workflow_dispatch:

jobs:
  build:
    name: build
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@master
    - name: Test image
      shell: pwsh
      run: |
        cd express
        docker build -m 4g -t cagrin/mssql-server-oldies:2014-express-pl --file 2014-express-pl.dockerfile .
        docker run --name 2014-express-pl-test -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=A.794613" -p 51433:1433 -m 4g -d cagrin/mssql-server-oldies:2014-express-pl
        Start-Sleep -Second 10
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "A.794613" -Query "IF SERVERPROPERTY('Edition') <> 'Express Edition (64-bit)' RAISERROR ('Edition is invalid', 16, 1)"
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "A.794613" -Query "IF SERVERPROPERTY('ProductVersion') <> '12.0.6433.1' RAISERROR ('ProductVersion is invalid', 16, 1)"
        Invoke-Sqlcmd -ServerInstance "localhost,51433" -Database "master" -Username "sa" -Password "A.794613" -Query "IF SERVERPROPERTY('Collation') <> 'Polish_CI_AS' RAISERROR ('Collation is invalid', 16, 1)"