name: Test images
on:
  workflow_dispatch:

jobs:
  test-images:
    name: Test images
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@v4
    - name: Pull all images
      shell: pwsh
      run: |
        ./developer/pull.ps1
    - name: Test all images
      shell: pwsh
      run: |
        ./developer/test.ps1