name: Test images
on:
  workflow_dispatch:

jobs:
  test-images:
    name: Test images
    runs-on: windows-2022
    steps:
    - uses: actions/checkout@master
    - name: Pull all images
      run: |
        docker pull cagrin/mssql-server-ltsc2022:2012-latest
        docker pull cagrin/mssql-server-ltsc2022:2014-latest
        docker pull cagrin/mssql-server-ltsc2022:2016-latest
        docker pull cagrin/mssql-server-ltsc2022:2017-latest
        docker pull cagrin/mssql-server-ltsc2022:2019-latest
        docker pull cagrin/mssql-server-ltsc2022:2012-latest-pl
        docker pull cagrin/mssql-server-ltsc2022:2014-latest-pl
        docker pull cagrin/mssql-server-ltsc2022:2016-latest-pl
        docker pull cagrin/mssql-server-ltsc2022:2017-latest-pl
        docker pull cagrin/mssql-server-ltsc2022:2019-latest-pl
        docker pull cagrin/mssql-server-ltsc2022:2012-latest-ua
        docker pull cagrin/mssql-server-ltsc2022:2014-latest-ua
        docker pull cagrin/mssql-server-ltsc2022:2016-latest-ua
        docker pull cagrin/mssql-server-ltsc2022:2017-latest-ua
        docker pull cagrin/mssql-server-ltsc2022:2019-latest-ua
    - name: Test all images
      shell: pwsh
      run: |
        ./developer/test.ps1