name: Test images
on:
  workflow_dispatch:

jobs:
  test-images:
    name: Test images
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@master
    - name: Pull base image
      run: docker pull mcr.microsoft.com/dotnet/framework/runtime:3.5-windowsservercore-ltsc2016
    - name: Test images
      shell: pwsh
      run: |
        ./developer/test.ps1